apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: {{ k8s_version }}
{% if ((k8s_external_etcd | default('')) != '') %}
etcd:
  external:
    endpoints:
    - {{k8s_external_etcd}}
{% endif %}
networking:
  podSubnet: {{k8s_pod_network_cidr}}

{% if ((k8s_external_api | default('')) != '') %}
apiServerCertSANs:
- "{{ k8s_external_api }}"
controlPlaneEndpoint: "{{k8s_external_api}}:6443"
{% endif %}
