apiVersion: kubeadm.k8s.io/v1alpha3
kind: ClusterConfiguration
kubernetesVersion: 1.13.0
{% if ((k8s_external_etcd | default('')) != '') %}
etcd:
  external:
    endpoints:
    - {{k8s_external_etcd}}
{% endif %}
networking:
  podSubnet: {{k8s_pod_network_cidr}}

{% if ((k8s_external_api | default('')) != '') %}
apiServerCertSANs:
- "{{ k8s_external_api }}"
controlPlaneEndpoint: "{{k8s_external_api}}:6443"
{% endif %}
