# From https://akomljen.com/kubernetes-nginx-ingress-controller/

- name: "Creation du repertoire contenant les deploiements de l'ingress demo"
  file:
    path: "{{k8s_ingress_demo_deployments_path}}"
    state: directory
    mode: 0755

- include_tasks: template_apply.yml 
  vars:
    path: "{{k8s_ingress_demo_deployments_path}}" 
    file: app-deployment.yaml

- include_tasks: template_apply.yml 
  vars:
    path: "{{k8s_ingress_demo_deployments_path}}" 
    file: app-service.yaml

- include_tasks: template_apply.yml 
  vars:
    path: "{{k8s_ingress_demo_deployments_path}}" 
    file: app-ingress.yaml



