- name: "Installation des packages necessaires a lxc"
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - lxc
    - lxc-templates
    - bridge-utils 
    - debootstrap 

- name: "Verification de l'existance du bridge labbr (lab bridge)"
  shell: "lxc network show {{lxc_bridge_name}}"
  register: bridge_exists
  changed_when: bridge_exists.rc != 0
  failed_when: False

- name: "Creation du bridge"
  shell: lxc network create {{lxc_bridge_name}} ipv6.address=none ipv4.address={{ lxc_bridge_address }}/{{ lxc_bridge_net_mask }} ipv4.nat=true
  when: bridge_exists.rc != 0

