lxc_container_name: lab
lxc_container_bridge_name: labbr
lxc_container_mac: 00:16:3e:13:7f:12
lxc_container_ipv4: 10.0.4.5
lxc_container_gateway: 10.0.4.1
lxc_container_net_mask: 24
lxc_container_http_proxy: http://10.0.4.1:8888
lxc_container_http_no_proxy: 
lxc_container_ssh_pub_key: ~/.ssh/id_rsa.pub
lxc_container_mounts: []

# lxc_container_mounts:
#   - src:  /data/lab/
#     target: /data/lab/
  