---

- import_playbook: host_prerequisites.yml 

- name: "Prerequis sur l'hote"
  hosts: lab_host
  become: True
  roles:
    - role: lxc
      vars:
        lxc_bridge_name: labbr
        lxc_bridge_address: 10.0.4.1
        lxc_bridge_net_mask: 24

- name: "Creation du cluster ETCD"
  hosts: lab_host
  become: True
  roles:
    - role: lxc_container
      vars:
        lxc_container_name: labetcd1
        lxc_container_bridge_name: labbr
        lxc_container_mac: 00:16:3e:13:7f:14
        lxc_container_ipv4: 10.0.4.14
        lxc_container_gateway: 10.0.4.1
        lxc_container_net_mask: 24
        lxc_container_http_proxy: "{{ http_proxy }}"
        lxc_container_http_no_proxy: 10.0.4.0/24,10.32.0.2/16,10.0.4.14,10.0.4.15,10.0.4.16
    - role: lxc_container
      vars:
        lxc_container_name: labetcd2
        lxc_container_bridge_name: labbr
        lxc_container_mac: 00:16:3e:13:7f:15
        lxc_container_ipv4: 10.0.4.15
        lxc_container_gateway: 10.0.4.1
        lxc_container_net_mask: 24
        lxc_container_http_proxy: "{{ http_proxy }}"
        lxc_container_http_no_proxy: 10.0.4.0/24,10.32.0.2/16,10.0.4.14,10.0.4.15,10.0.4.16
    - role: lxc_container
      vars:
        lxc_container_name: labetcd3
        lxc_container_bridge_name: labbr
        lxc_container_mac: 00:16:3e:13:7f:16
        lxc_container_ipv4: 10.0.4.16
        lxc_container_gateway: 10.0.4.1
        lxc_container_net_mask: 24
        lxc_container_http_proxy: "{{ http_proxy }}"
        lxc_container_http_no_proxy: 10.0.4.0/24,10.32.0.2/16,10.0.4.14,10.0.4.15,10.0.4.16

- name: "Creation du cluster HAPROXY"
  hosts: lab_host
  become: True
  roles:
    - role: lxc_container
      vars:
        lxc_container_name: labha1
        lxc_container_bridge_name: labbr
        lxc_container_mac: 00:16:3e:13:7f:11
        lxc_container_ipv4: 10.0.4.11
        lxc_container_gateway: 10.0.4.1
        lxc_container_net_mask: 24
        lxc_container_http_proxy: "{{ http_proxy }}"
        lxc_container_http_no_proxy: 10.0.4.0/24,10.32.0.2/16
    - role: lxc_container
      vars:
        lxc_container_name: labha2
        lxc_container_bridge_name: labbr
        lxc_container_mac: 00:16:3e:13:7f:12
        lxc_container_ipv4: 10.0.4.12
        lxc_container_gateway: 10.0.4.1
        lxc_container_net_mask: 24
        lxc_container_http_proxy: "{{ http_proxy }}"
        lxc_container_http_no_proxy: 10.0.4.0/24,10.32.0.2/16

- name: "Creation du container k8s master"
  hosts: lab_host
  become: True
  roles:
    - role: lxc_container
      vars:
        lxc_container_name: labmaster1
        lxc_container_bridge_name: labbr
        lxc_container_mac: 00:16:3e:13:7f:04
        lxc_container_ipv4: 10.0.4.4
        lxc_container_gateway: 10.0.4.1
        lxc_container_net_mask: 24
        lxc_container_http_proxy: "{{ http_proxy }}"
        lxc_container_http_no_proxy: 10.0.4.0/24,10.32.0.2/16,10.0.4.10
    - role: lxc_container
      vars:
        lxc_container_name: labmaster2
        lxc_container_bridge_name: labbr
        lxc_container_mac: 00:16:3e:13:7f:05
        lxc_container_ipv4: 10.0.4.5
        lxc_container_gateway: 10.0.4.1
        lxc_container_net_mask: 24
        lxc_container_http_proxy: "{{ http_proxy }}"
        lxc_container_http_no_proxy: 10.0.4.0/24,10.32.0.2/16,10.0.4.10

- name: "Creation du container k8s slave"
  hosts: lab_host
  become: True
  roles:
    - role: lxc_container
      vars:
        lxc_container_name: labslave1
        lxc_container_bridge_name: labbr
        lxc_container_mac: 00:16:3e:13:7f:06
        lxc_container_ipv4: 10.0.4.6
        lxc_container_gateway: 10.0.4.1
        lxc_container_net_mask: 24
        lxc_container_http_proxy: "{{ http_proxy }}"
        lxc_container_http_no_proxy: 10.0.4.0/24,10.32.0.2/16,10.0.4.10
    - role: lxc_container
      vars:
        lxc_container_name: labslave2
        lxc_container_bridge_name: labbr
        lxc_container_mac: 00:16:3e:13:7f:07
        lxc_container_ipv4: 10.0.4.7
        lxc_container_gateway: 10.0.4.1
        lxc_container_net_mask: 24
        lxc_container_http_proxy: "{{ http_proxy }}"
        lxc_container_http_no_proxy: 10.0.4.0/24,10.32.0.2/16,10.0.4.10


