---

# la configuration d'un etcd depend de tout le cluster etcd,
# et le cluster haproxy doit etre configure
- name: "On force le gathering ansible"
  hosts: lb,etcd
  tasks: [ ]  

- name: "Installation de etcd"
  hosts: etcd
  serial: True
  roles:
    - role: etcd
      vars:
        etcd_group_name: etcd

- name: "Enregistrement du cluster etcd dans ha_proxy"
  hosts: lb
  serial: True
  roles:
    - role: haproxy_tcp_config
      vars:
        haproxy_config_name: 03-etcd
        haproxy_config_bind_port: 2379
        backend_nodes_group: etcd
        backend_nodes_group_if: eth0
        backend_nodes_group_port: 2379

        # - name: node1
        #   host: 10.0.4.14
        #   port: 2379
        # - name: node2
        #   host: 10.0.4.15
        #   port: 2379
        # - name: node3
        #   host: 10.0.4.16
        #   port: 2379
