

- name: "Installation de haproxy/keealived (Master)"
  hosts: lb_master
  roles:
    - role: haproxy
      vars: 
        haproxy_vip: 10.0.4.10
        haproxy_master: true
        haproxy_eth: eth0

- name: "Installation de haproxy/keealived  (Slave)"
  hosts: lb_slave
  roles:
    - role: haproxy
      vars: 
        haproxy_vip: 10.0.4.10
        haproxy_master: false
        haproxy_eth: eth0