
- name: "Creation du container slave"
  hosts: lab_host
  become: True
  roles:
    - role: lxc_container
      vars:
        lxc_container_name: labha1
        lxc_container_bridge_name: labbr
        lxc_container_mac: 00:16:3e:13:7f:21
        lxc_container_ipv4: 10.0.4.11
        lxc_container_gateway: 10.0.4.1
        lxc_container_net_mask: 24
        lxc_container_http_proxy: http://10.0.4.1:8888/
        lxc_container_http_no_proxy: 10.0.4.0/24,10.32.0.2/16
    - role: lxc_container
      vars:
        lxc_container_name: labha2
        lxc_container_bridge_name: labbr
        lxc_container_mac: 00:16:3e:13:7f:22
        lxc_container_ipv4: 10.0.4.12
        lxc_container_gateway: 10.0.4.1
        lxc_container_net_mask: 24
        lxc_container_http_proxy: http://10.0.4.1:8888/
        lxc_container_http_no_proxy: 10.0.4.0/24,10.32.0.2/16
  tasks:
    - add_host:
        name: 10.0.4.11
        ansible_user: root
        groups: 
        - lb_master
    - add_host:
        name: 10.0.4.12
        ansible_user: root
        groups: 
        - lb_slave

- name: "Installation de haproxy/keealived (Master)"
  hosts: lb_master
  roles:
    - role: haproxy
      vars: 
        haproxy_vip: 10.0.4.10
        haproxy_master: true
        haproxy_eth: eth0

- name: "Installation de haproxy/keealived  (Slave)"
  hosts: lb_slave
  roles:
    - role: haproxy
      vars: 
        haproxy_vip: 10.0.4.10
        haproxy_master: false
        haproxy_eth: eth0