
- name: "Installation des packages necessaires"
  hosts: lab_host
  become: True
  tasks:
    - package:
        name: "{{ item }}"
        state: present
      with_items:
        - lxc
        - lxd
        - python-lxc
  # roles:
  #   - role: certificate_authority
  #     vars:
  #       certificate_authority_key: /var/lab/lab_certificate_authority.key
  #       certificate_authority_pem: /var/lab/lab_certificate_authority.crt
