
- name: "Installation des packages necessaires"
  hosts: lab_host
  become: True
  tasks:
    - package:
        name: "{{ item }}"
        state: present
      with_items:
        - lxc
        - python-lxc
