# la configuration d'un etcd depend de tout le cluster kubemaster,
# et le cluster haproxy doit etre configure
- name: "On force le gathering ansible"
  hosts: lb,kubecluster
  tasks: [ ]

- name: "Enregistrement des ingress dans ha_proxy"
  hosts: lb
  serial: True
  roles:
    - role: haproxy_tcp_config
      vars:
        haproxy_config_name: 05-ingress-http
        haproxy_config_bind_port: 80
        backend_nodes_group: kubecluster
        backend_nodes_group_if: eth0
        backend_nodes_group_port: 30080
    - role: haproxy_tcp_config
      vars:
        haproxy_config_name: 06-ingress-https
        haproxy_config_bind_port: 443
        backend_nodes_group: kubecluster
        backend_nodes_group_if: eth0
        backend_nodes_group_port: 30443

- name: Installation de l'ingress
  hosts: kubemaster_leader
  roles:
    - k8s_ingress



