---
- import_playbook: nodes_prerequisites.yml
- import_playbook: haproxy.yml
- import_playbook: etcd.yml
- import_playbook: k8scluster.yml 
- import_playbook: k8svolumes.yml
- import_playbook: ingress.yml
