#============================================
# Preparation de l'hote
#============================================
- name: "Lxc"
  hosts: lab_host
  become: True
  roles:
    - role: lxc
      vars:
        lxc_bridge_name: labbr
        lxc_bridge_address: 10.0.4.1
        lxc_bridge_net_mask: 24
#============================================
# Creation du kube_master
#============================================
# 1) Lxc
- name: "Lxc"
  hosts: lab_host
  become: True
  roles:
    - role: lxc_container
      vars:
        lxc_container_name: labmaster
        lxc_container_bridge_name: labbr
        lxc_container_mac: 00:16:3e:13:7f:12
        lxc_container_ipv4: 10.0.4.5
        lxc_container_gateway: 10.0.4.1
        lxc_container_net_mask: 24
        lxc_container_http_proxy: http://10.0.4.1:8888
  tasks:
    - add_host:
        name: 10.0.4.5
        ansible_user: root
        groups: 
        - kubemaster

- name: "Kubemaster"
  hosts: kubemaster
  tasks:
    - debug:
        msg: "Hello from kubemaster"
  roles:
    - role: k8s_master
