

- debug:
    msg: "kubeadm init --pod-network-cidr={{ k8s_pod_network_cidr }} --apiserver-advertise-address={{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }} --ignore-preflight-errors=all"

- name: "Initialisation de kubernetes"
  shell: "kubeadm init --pod-network-cidr={{ k8s_pod_network_cidr }} --apiserver-advertise-address={{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }} --ignore-preflight-errors=all &> /root/kubeinit.log"
  args:
    creates: /etc/kubernetes/admin.conf

- name: "Initialisation du repertoire configuration utilisateur."
  file:
    path: /root/.kube
    state: directory
    mode: "u=rwx,g=,o="
  
- name: Ansible copy files remote to remote
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    owner: root
    group: root
    mode: "u=rw,g=,o="
    remote_src: yes

- fail:
   msg: "Stop there!... le reste est fait a la main pour l'instant..."

- name: Installation de weave
  shell: |
    kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')" &> /root/weave.initialized
    kubectl taint nodes --all node-role.kubernetes.io/master- &&> /root/weave.initialized
  args:
    creates: /root/weave.initialized


# - name: Installation de flannel
#   shell: |
#     kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml &> /root/flannel.initialized
#     kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-rbac.yml &>> /root/flannel.initialized
#     kubectl taint nodes --all node-role.kubernetes.io/master- &&> /root/flannel.initialized
#   args:
#     creates: /root/flannel.initialized
