- name: "Installation de docker"
  package:
    name: docker.io
    state: present

- name: "Parametrage du service docker"
  service:
    name: docker
    enabled: yes
    state: started

- name: "Installation des packages necessaires a l'import de clef"
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - curl
    - gnupg2

- name: Add an Apt signing key, will not download if present
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: "Ajout du repo kubernetes"
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
  register: repo_added

- name: "Update du cache apt"
  apt:
    update_cache: yes
  when: repo_added is changed


- name: "Installation de kubernetes"
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - kubeadm
    - kubelet
    - kubernetes-cni

- name: "Initialisation de kubernetes"
  shell: "kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address={{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }} --kubernetes-version stable-1.11 --ignore-preflight-errors=all"
  args:
    creates: /root/kubernetes.initialized

- name: "Initialisation du repertoire configuration utilisateur."
  file:
    path: /root/.kube
    state: directory
    mode: "u=rwx,g=,o="
  
- name: Ansible copy files remote to remote
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    owner: root
    group: root
    mode: "u=rw,g=,o="
    remote_src: yes

- name: Installation de flannel
  shell: |
    kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-rbac.yml
    kubectl taint nodes --all node-role.kubernetes.io/master-



